export const EMBEDDING_DIMS = {
  VISUAL: 512,
  TEXT: 384,
  FACE: 512,
} as const;

export const SEARCH = {
  VISUAL_CANDIDATE_POOL: 50,
  FACE_MATCH_THRESHOLD: 0.5,
  FACE_BOOST: 0.5,
  VISUAL_WEIGHT: 0.7,
  TEXT_WEIGHT: 0.3,
  DEFAULT_TOP_K: 5,
  MAX_TOP_K: 50,
} as const;

export const INDEXING = {
  SCENE_DETECT_THRESHOLD: 27.0,
  MAX_VIDEO_SIZE_BYTES: 2 * 1024 * 1024 * 1024,
  MAX_VIDEO_DURATION_SECONDS: 3600,
} as const;

export const API = {
  RATE_LIMIT_SEARCH: 100,
  RATE_LIMIT_INDEX: 10,
  RATE_LIMIT_WINDOW_MS: 60_000,
  KEY_PREFIX: 'tmpo_',
} as const;
